const constant = {
    Invalid_credentials: "Invalid credentials",
    User_login_successfully: 'User login successfully',
    Record_not_found: "Record not found",

    Change_password_link_successfully_send: 'Change password link successfully send',
    Passwords_do_not_match: "Passwords do not match",
    Password_change_successfully: "Password change successfully",
    Server_Error: "Server Error",
    Data_get_successfully: "Data get successfully",
    Profile_updated_successfully: "Profile updated successfully",
    Email_Template_List: "Email Template List",
    Post_List: "Post List",
    Post_Delete_List: "Delete post successfully",
    Email_template_successfully_update: "Email template successfully update",
    Cms_Page_List: "Cms Page List",
    Cms_Page_successfully_update: "Cms Page successfully update",
    Invalid_page_number_should_start_with_1: "Invalid page number, should start with 1",
    // This_user_not_found: "This user not found",
    User_successfully_updated: "User successfully updated",
    Delete_user_successfully: "Delete user successfully",
    OTP_verified: "OTP verified",
    Otp_does_not_match_or_expired: "Otp does not match or expired",
    Record_not_found_or_you_have_not_verified_your_email_address: "Record not found or you have not verified your email address",
    Record_not_found: "Record not found.",
    You_have_not_verified_your_email_address: "Please verify email sent on the mail to log in to the account ",
    User_login_successfully: "User login successfully",
    Invalid_credentials: "Invalid credentials",
    Password_does_not_match: "Password does not match",
    Email_address_already_exists: "Email address already exists",
    Something_went_wrong: "Something went wrong",
    New_user_created_Verification_link_is_sent_to_given_email_address: "New user created.Verification link is sent to given email address",
    Token_expired: "Token expired",
    Your_account_is_verified: "Your account is verified",
    Record_not_exists_or_you_are_not_verified: "Record not exists or you are not verified",
    Un_like: "Un-like",
    Like: "Like",
    User_not_exists: "User not exists",
    Please_provide_all_fields: "Please provide all fields",
    New_post_created: "New post created",
    This_post_does_not_exists: "This post does not exists",
    Please_provide_user_id: "Please provide user id",
    User_name_can_not_be_empty: "User name can not be empty!",
    Minimum_3_characters_required: "Minimum 3 characters required!",
    Email_name_can_not_be_empty: "Email name can not be empty!",
    Invalid_email_address: "Invalid email address!",
    Password_can_not_be_empty: "Password can not be empty!",
    Gender_is_required: "Gender is required!",
    Confirm_Password_can_not_be_empty: "Confirm Password can not be empty!",
    Passwords_dont_match: "Passwords don't match.",
    username_can_not_be_empty: "username can not be empty!",
    fullname_can_not_be_empty: "fullname can not be empty!",
    name_can_not_be_empty: "name can not be empty!",
    Title_can_not_be_empty: "Title can not be empty!",
    Description_can_not_be_empty: "Description can not be empty!",
    Subject_can_not_be_empty: "Subject can not be empty!",

    Global_Settings_Added: "Global Settings added successfully",
    Global_Settings_Updated: "Global Settings updated successfully",
    title_can_not_be_empty: "Title can not be empty!",
    slug_can_not_be_empty: "Slug can not be empty!",
    metaTitle_can_not_be_empty: "Meta Title can not be empty!",
    metaDiscription_can_not_be_empty: "meta Discription can not be empty!",

    Category_Added: "Category added successfully",
    Category_Updated: "Category updated successfully",
    Category_Deleted: "Category deleted successfully",
    Category_not_found: "Category not found",
    Category_not_deleted: "Category not deleted",

    Subcategory_not_found: "Subcategory not found",
    Subcategory_Added: " Subcategory added successfully",
    Subcategory_Updated: " Subcategory updated successfully",
    Subcategory_Deleted: " Subcategory deleted successfully",
    Subcategory_not_found: "Subcategory not found",
    Subcategory_not_deleted: "Subcategory not deleted",

    connectionSize_Added: " Connection Size added successfully",
    connectionSize_Updated: " Connection Size updated successfully",
    connectionSize_Deleted: " Connection Size deleted successfully",
    connectionSize_not_found: "Connection Size not found",
    connectionSize_not_deleted: "Connection Size not deleted",

    meterServiceCharge_Added: " meter Service Charge added successfully",
    meterServiceCharge_Updated: " meter Service Charge updated successfully",
    meterServiceCharge_Deleted: " meter Service Charge deleted successfully",
    meterServiceCharge_not_found: "meter Service Charge not found",
    meterServiceCharge_not_deleted:"meter Service Charge not deleted",

    meterStatusCode_Added: " meter Status Code added successfully",
    meterStatusCode_Updated: " meter Status Code updated successfully",
    meterStatusCode_Deleted: " meter Statu sCode deleted successfully",
    meterStatusCode_not_found: "meter Status Code not found",
    meterStatusCode_not_deleted: "meter Status Code not deleted", 

    connectionType_Added: " Connection Type added successfully",
    connectionType_Updated: " Connection Type updated successfully",
    connectionType_Deleted: " Connection Type deleted successfully",
    connectionType_not_found: "Connection Type not found",
    connectionType_not_deleted: "Connection Type not deleted",


    Attribute_Added: "Attribute added successfully",
    Attribute_Updated: "Attribute updated successfully",
    Attribute_Deleted: "Attribute deleted successfully",
    Post_Featued_Updated: "Post Featured Updated",


    Slab_not_found: "Slab not found",
    Slab_Added: " Slab added successfully",
    Slab_Updated: " Slab updated successfully",
    Slab_Deleted: " Slab deleted successfully",
    Slab_not_found: "Slab not found",
    Slab_not_deleted: "Slab not deleted",

}
module.exports = constant;
